name: hello_robotics
version: '0.1'
summary: Hello World, of Robotics
description: |
  This example launches a ROS 2 talker or listener.

confinement: devmode
base: core22

parts:
  ros-demos:
    plugin: colcon
    source: https://github.com/McDoogen/HelloRobotics
    source-branch: main

apps:
  hello_robotics_subscriber:
    command: opt/ros/humble/bin/ros2 run hello_robotics subscriber_node
    extensions: [ros2-humble]
  hello_robotics_publisher:
    command: opt/ros/humble/bin/ros2 run hello_robotics publisher_node 
    extensions: [ros2-humble]
  hello_robotics_hello:
    command: opt/ros/humble/bin/ros2 run hello_robotics hello_node
    extensions: [ros2-humble]