name: hello-robotics
version: '0.1'
summary: Hello World, of Robotics
description: |
  This example launches a ROS 2 talker or listener.

confinement: devmode
base: core22

parts:
  hello-robotics-demo:
    plugin: colcon
    source: https://github.com/McDoogen/HelloRobotics.git
    source-branch: main
    stage-packages: [ros-humble-ros2launch]

apps:
  hello-robotics-subscriber:
    command: opt/ros/humble/bin/ros2 run hello_robotics subscriber_node
    extensions: [ros2-humble]
  hello-robotics-publisher:
    command: opt/ros/humble/bin/ros2 run hello_robotics publisher_node 
    extensions: [ros2-humble]
  hello-robotics-hello:
    command: opt/ros/humble/bin/ros2 run hello_robotics hello_node
    extensions: [ros2-humble]